# Generated by Django 2.2.17 on 2020-12-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaperCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_zh', models.CharField(max_length=1024, verbose_name='分类名称')),
                ('name_en', models.CharField(max_length=1024, verbose_name='category name')),
            ],
            options={
                'verbose_name': '论文类别',
                'verbose_name_plural': '论文类别',
                'db_table': 'PaperCategory',
            },
        ),
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=1024, verbose_name='组织')),
                ('name', models.CharField(max_length=1024, verbose_name='姓名')),
                ('image', models.FileField(blank=True, null=True, upload_to='', verbose_name='头像')),
                ('email', models.CharField(blank=True, max_length=128, null=True, verbose_name='邮箱')),
            ],
            options={
                'verbose_name': '论文作者',
                'verbose_name_plural': '论文作者',
                'db_table': 'Researcher',
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024, verbose_name='标题')),
                ('publish_on', models.CharField(max_length=1024, verbose_name='发表于')),
                ('time', models.DateField(verbose_name='时间')),
                ('bibTex', models.TextField()),
                ('categories', models.ManyToManyField(to='xb_paper.PaperCategory', verbose_name='论文类别')),
                ('researchers', models.ManyToManyField(to='xb_paper.Researcher', verbose_name='作者')),
            ],
            options={
                'verbose_name': '论文',
                'verbose_name_plural': '论文',
                'db_table': 'Paper',
            },
        ),
    ]
