# Generated by Django 2.2 on 2020-12-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xb_paper', '0002_auto_20201205_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcher',
            name='email',
            field=models.CharField(default='', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='image',
            field=models.FileField(default='#', null=True, upload_to=''),
        ),
    ]
