# Generated by Django 2.2 on 2020-12-06 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xb_paper', '0003_auto_20201206_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='page',
        ),
    ]
