# Generated by Django 2.2 on 2020-11-25 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xb_paper', '0003_remove_researcher_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcher',
            name='image',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
    ]
