# Generated by Django 2.2 on 2020-12-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xb_paper', '0004_remove_paper_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='time',
            field=models.DateField(),
        ),
    ]
