# Generated by Django 2.2 on 2020-11-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xb_paper', '0004_researcher_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcher',
            name='email',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
