# Generated by Django 2.2 on 2020-12-06 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xb_paper', '0005_auto_20201206_1808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper',
            old_name='title',
            new_name='title_en',
        ),
    ]
