# Generated by Django 2.2 on 2020-12-06 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xb_paper', '0006_auto_20201206_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='title_zh',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
    ]
