# Generated by Django 2.2 on 2020-12-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xb_paper', '0007_paper_title_zh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='bibTex',
            field=models.TextField(),
        ),
    ]
