# Generated by Django 2.2 on 2020-12-06 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xb_paper', '0009_remove_paper_title_zh'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper',
            old_name='title_en',
            new_name='title',
        ),
    ]
