# Generated by Django 2.2 on 2020-12-06 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xb_paper', '0010_auto_20201206_1909'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paper',
            options={'verbose_name': '论文', 'verbose_name_plural': '论文'},
        ),
        migrations.AlterModelOptions(
            name='papercategory',
            options={'verbose_name': '论文类别', 'verbose_name_plural': '论文类别'},
        ),
        migrations.AlterModelOptions(
            name='researcher',
            options={'verbose_name': '论文作者', 'verbose_name_plural': '论文作者'},
        ),
    ]
