# Generated by Django 2.2 on 2020-11-29 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xb_log', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslog',
            name='path',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
